/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TaskDto } from '../../models/task-dto';
import { TaskReqDto } from '../../models/task-req-dto';

export interface TaskControllerCreateTask$Params {
      body: TaskReqDto
}

export function taskControllerCreateTask(http: HttpClient, rootUrl: string, params: TaskControllerCreateTask$Params, context?: HttpContext): Observable<StrictHttpResponse<TaskDto>> {
  const rb = new RequestBuilder(rootUrl, taskControllerCreateTask.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TaskDto>;
    })
  );
}

taskControllerCreateTask.PATH = '/task';
