/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TaskDto } from '../../models/task-dto';

export interface TaskControllerUpdateTask$Params {
  id: string;
}

export function taskControllerUpdateTask(http: HttpClient, rootUrl: string, params: TaskControllerUpdateTask$Params, context?: HttpContext): Observable<StrictHttpResponse<TaskDto>> {
  const rb = new RequestBuilder(rootUrl, taskControllerUpdateTask.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TaskDto>;
    })
  );
}

taskControllerUpdateTask.PATH = '/task/{id}';
