/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TaskReqDto {

  /**
   * The description of the task
   */
  description: string;
  status: 'IN_PROGRESS' | 'COMPLETED';

  /**
   * The title of the task
   */
  title: string;
}
