/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TaskDto {

  /**
   * Timestamp when task was created
   */
  createdAt: string;

  /**
   * The description of the task
   */
  description: string;

  /**
   * The id of the task
   */
  id: string;
  status: 'IN_PROGRESS' | 'COMPLETED';

  /**
   * The title of the task
   */
  title: string;
}
